services:
  postgres:
    image: postgres:15-alpine
    container_name: laviepet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laviepet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laviepet-network

  redis:
    image: redis:7-alpine
    container_name: laviepet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laviepet-network

volumes:
  postgres_data:

networks:
  laviepet-network:
    driver: bridge